<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Result;

class ResultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('results')->insert([
            [
                'slug' => 'k4d',
                'title' => 'Kampot 4D',
                'logo' => 'https://4dlivegame.com/static/img/markets/kampot4d_0.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => 'Setiap 1 Jam',
                'tutup' => 'Setiap 1 Jam',
                'periode' => '4478',
                'type' => '1',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'sgp',
                'title' => 'Singapore',
                'logo' => 'https://4dlivegame.com/static/img/markets/singapore.webp',
                'keluaran' => '9926',
                'tanggal' => '20-07-2024',
                'buka' => '17:20',
                'tutup' => '17:40',
                'periode' => '2306',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'hkg',
                'title' => 'Hongkong',
                'logo' => 'https://4dlivegame.com/static/img/markets/hkg.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '23:00',
                'tutup' => '22:00',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'ber',
                'title' => 'Berlin',
                'logo' => 'https://4dlivegame.com/static/img/markets/berlin.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '24:00',
                'tutup' => '23:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'tmr',
                'title' => 'Timor',
                'logo' => 'https://4dlivegame.com/static/img/markets/kampot4d_0.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '12:00',
                'tutup' => '11:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'bei',
                'title' => 'Beijing',
                'logo' => 'https://4dlivegame.com/static/img/markets/beijing.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '13:00',
                'tutup' => '12:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'ams',
                'title' => 'Amsterdam',
                'logo' => 'https://4dlivegame.com/static/img/markets/amsterdam.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '13:00',
                'tutup' => '12:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'tky',
                'title' => 'Tokyo',
                'logo' => 'https://4dlivegame.com/static/img/markets/tokyo.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '14:00',
                'tutup' => '13:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'sol',
                'title' => 'Seoul',
                'logo' => 'https://4dlivegame.com/static/img/markets/seoul.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '15:30',
                'tutup' => '15:10',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'bgk',
                'title' => 'Bangkok',
                'logo' => 'https://4dlivegame.com/static/img/markets/bangkok.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '16:00',
                'tutup' => '15:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'mnl',
                'title' => 'Manila',
                'logo' => 'https://4dlivegame.com/static/img/markets/manila.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '20:00',
                'tutup' => '19:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'bcl',
                'title' => 'Barcelona',
                'logo' => 'https://4dlivegame.com/static/img/markets/barcelona.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '21:30',
                'tutup' => '21:00',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'rom',
                'title' => '4DRome',
                'logo' => 'https://4dlivegame.com/static/img/markets/4drome.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '22:50',
                'tutup' => '22:15',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'bul',
                'title' => 'Bullseye',
                'logo' => 'https://4dlivegame.com/static/img/markets/bullseye.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '13:15',
                'tutup' => '11:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'sib',
                'title' => 'SiberiaPools',
                'logo' => 'https://4dlivegame.com/static/img/markets/siberiapools.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '00:15',
                'tutup' => '23:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'hkg47',
                'title' => 'Hongkong47',
                'logo' => 'https://4dlivegame.com/static/img/markets/hkg47.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '23:00',
                'tutup' => '22:00',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'hkg49',
                'title' => 'Hongkong49',
                'logo' => 'https://4dlivegame.com/static/img/markets/hkg49.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '14:00',
                'tutup' => '13:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'mgm',
                'title' => 'Magnum4D',
                'logo' => 'https://4dlivegame.com/static/img/markets/magnum4d.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '18:50',
                'tutup' => '17:50',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'pcso',
                'title' => 'PCSO',
                'logo' => 'https://4dlivegame.com/static/img/markets/pcso.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '20:20',
                'tutup' => '19:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'slug' => 'syd',
                'title' => 'SydneyPools',
                'logo' => 'https://4dlivegame.com/static/img/markets/sydneypools.webp',
                'keluaran' => '3794',
                'tanggal' => '21-07-2024',
                'buka' => '13:50',
                'tutup' => '13:30',
                'periode' => '4478',
                'type' => '2',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ]
        ]);
    }
}
